---
- name: Ansible Delete user
  hosts: Ansible_Node.faysalbank.com
  remote_user: root
  become: yes
  tasks:
    - name: Remove the user
      ansible.builtin.user:
        name: test
        state: absent
        remove: yes
