---
- name: Ansible Modify user
  hosts: Ansible_Node.faysalbank.com
  remote_user: root
  tasks:
    - name: Modify the user
      ansible.builtin.user:
        name: test
        uid: 1001
        state: present
        comment: Test User    
