---
- name: Ansible Delete user
  hosts: at.odomain.local
  remote_user: root
  become: yes
  tasks:
    - name: Remove the user
      ansible.builtin.user:
        name: test
        state: absent
        remove: yes
