---
- name: Ansible Create user
  hosts: Ansible_Node.faysalbank.com
  remote_user: root
  tasks:
    - name: Add the user
      ansible.builtin.user:
        name: test
        comment: Test User    
